added tests
feedhenry-raincatcher/raincatcher-core pull request #32
Opened 2017-06-30 12:50 UTC by spriadka

## Motivation

## Description
A few sentences describing the overall goals of the pull request's commits.

## Progress
- [ ]
- [ ] Unit tests
- [ ] Documentation

## Additional Notes

2017-06-30 12:51 UTC, spriadka commented
@wtrocki Please review this PR

2017-07-03 12:24 UTC, paolobueno commented on integration/vehicle-inspection/test/InMemoryTaskRepositoryTest.ts
> +            inMemoryTaskRepository.createMany([new BaseTask(), new BaseTask()]);
could move the common steps for each method to a `beforeEach`

2017-07-03 12:30 UTC, paolobueno commented
Nice start, are you going to add tests for the other repositories in the example?
If we keep the interfaces in the wfm repo, I'd like to move some of these tests there and use them from the example, similar to what's being done here: https://github.com/feedhenry-raincatcher/raincatcher-core/blob/master/client/wfm/test/Task/BaseTask.ts#L12 (the BaseTask implementation is using tests from the suite that just targets the original interface)

2017-07-03 12:43 UTC, paolobueno commented on integration/vehicle-inspection/test/InMemoryTaskRepositoryTest.ts
> +        it('Should construct repository with no tasks',function(){
can you use 2 spaces for identation?

2017-07-03 12:44 UTC, paolobueno requested changes
A few minor comments, and it's missing tests for the other repositories

2017-07-05 12:05 UTC, wtrocki commented
Closing as stale PR. @paolobueno Feel free to integrate this into your own work and fix remaining problems.

2017-07-05 12:05 UTC, closed without merging