RAINCATCH-1040
feedhenry-raincatcher/raincatcher-core pull request #39
Opened 2017-07-10 11:50 UTC by austincunningham

## Motivation
No logger implemented on wfm module
## Description
- Add the loggers as dependencies on the constructors of the classes that will use them
- Replace existing console statements with logger module calls
- include additional logging statements for completeness (info and other verbosities)
- Update unit tests to inject the logger dependencies

## Progress
- [x] Add the loggers as dependencies on the constructors of the classes that will use them
- [x] Replace existing console statements with logger module calls
- [ ] include additional logging statements for completeness (info and other verbosities)
- [ ] Update unit tests to inject the logger dependencies
- [x] Unit tests
- [x] Documentation

## Additional Notes

2017-07-10 14:28 UTC, wtrocki requested changes
Logger should be injected to the module

2017-07-10 15:23 UTC, paolobueno commented on .github/CODEOWNERS
> +*       @wtrocki @austincunningham @witmicko @paolobueno
:+1:

2017-07-10 15:50 UTC, JameelB commented on .github/CODEOWNERS
> +*       @wtrocki @austincunningham @witmicko @paolobueno
mind adding me to this too please? :D

2017-07-10 15:54 UTC, paolobueno commented on client/wfm/src/executor/Executor.ts
> +const log: Logger = new ConsoleLogger();
not used here since this is the interface definition

2017-07-10 15:55 UTC, paolobueno commented on client/wfm/src/executor/ExecutorImpl.ts
> +const log: Logger = new ConsoleLogger();
this should be injected by the app that's using this class via the constructor:
```
constructor(public process: Process, public repository: ExecutorRepository, protected log Logger) {
```

2017-07-10 15:56 UTC, paolobueno commented on client/wfm/src/task/BaseTask.ts
>        // TODO: replace with logger object
remove TODO comments that are done :slightly_smiling_face:

2017-07-12 08:56 UTC, closed without merging

2017-07-12 08:56 UTC, austincunningham commented
blocked by code updates